### ISSUE TITLE
Add ignoreExtraRows option

### ISSUE THREAD

**Issue by cogentParadigm** [ingenerator/behat-tableassert#6]
Thanks for sharing this! I'd like to have an ignoreExtraRows option. Is that something you would consider adding or accept a pull request for?

**Comment by acoulton** [comment]
Hey, it's unlikely we'll have time to work on adding it in the near future but we'd consider a pull request (with appropriate tests etc). 

I can potentially see it being useful, off the top of my head I'm not quite sure how it would be implemented (conceptually or in terms of how the current code does the comparison). 

How would you differentiate between an extra row and one which was expected but the content of the columns didn't match? I guess you could depend on some fixed identifier column - which would also allow an ignoreRowSequence option?

The challenge is making sure that on a failure it's obvious whether a row is outright missing, or just so different from the expected value(s) that it's been treated as an ignored extra row. If that makes sense?

**Comment by cogentParadigm** [comment]
I basically just wanted to validate the content of a CSV from the top down to a certain point. However, I got this accomplished just by trimming the extra rows off the end before the comparison if the table I'm validating has more rows than the example table.

Thanks for the consideration.

**Comment by acoulton** [comment]
@cogentParadigm thanks for the feedback and glad you found a solution
